import string

BLACK = 0, 0, 0
RED = 255, 0, 0
GREEN = 0, 255, 0
BLUE = 0, 0, 255
WHITE = 255, 255, 255
GRAY = 180, 180, 180
YELLOW = 255, 255, 0

MAX_DURATION = 60000  # ms
DEFAULT_FPS = 30

FIXATION = 'FIXATION'
POST_FIXATION_MASK = 'POST_FIXATION_MASK'
STIMULUS = 'STIMULUS'
POST_STIMULUS_MASK = 'POST_STIMULUS_MASK'
CUE = 'CUE'
POST_CUE_MASK = 'POST_CUE_MASK'
RESPONSE = 'RESPONSE'
FEEDBACK = 'FEEDBACK'

# In millis
DEFAULT_DURATIONS = {
    FIXATION: MAX_DURATION,
    POST_FIXATION_MASK: 500,
    STIMULUS: 50,
    POST_STIMULUS_MASK: 1,
    CUE: 500,
    POST_CUE_MASK: 1,
    RESPONSE: MAX_DURATION,
    FEEDBACK: MAX_DURATION
}

ALPHA = set(string.ascii_uppercase)
ALPHANUM = ALPHA.union(string.digits)
VOWELS = set('AEIOUY')
CONSONANTS = ALPHA.difference(VOWELS)


# functions
def NO_OP(*args, **kwargs):
    pass
